version: "3.9"
services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    volumes:
      - ./app:/var/www/symfony/
    container_name: nginx
    depends_on:
      - php
    ports:
      - "${APP_PORT}:80"
  
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: symfony_bot
    volumes:
      - ./app:/var/www/symfony
    depends_on:
      - db

  db: 
    image: mariadb:10.5
    container_name: mariadb_bot
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: sfUser
      MYSQL_PASSWORD: sfPassword
    volumes:
      - ./docker/database:/var/lib/mysql